const collegeDegrees = [
    "Bachelor of Science (B.Sc.)",
    "Bachelor of Arts (B.A.)",
    "Bachelor of Engineering (B.Eng.)",
    "Bachelor of Technology (B.Tech.)",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Computer Science (B.Comp.Sc.)",
    "Bachelor of Fine Arts (BFA)",
    "Master of Science (M.Sc.)",
    "Master of Arts (M.A.)",
    "Master of Engineering (M.Eng.)",
    "Master of Business Administration (MBA)",
    "Master of Technology (M.Tech.)",
    "Master of Computer Science (M.Comp.Sc.)",
    "Doctor of Philosophy (Ph.D.)",
    "Doctor of Medicine (M.D.)",
    "Doctor of Dental Medicine (DMD)",
    "Doctor of Veterinary Medicine (DVM)",
    "Juris Doctor (J.D.)",
    "Doctor of Pharmacy (Pharm.D.)",
    "Master of Public Health (M.P.H.)",
    "Master of Social Work (M.S.W.)",
    "Master of Education (M.Ed.)",
    "Master of Fine Arts (MFA)",
    "Associate of Science (A.S.)",
    "Associate of Arts (A.A.)",
    "Associate of Applied Science (A.A.S.)",
    "Associate of Business Administration (ABA)",
    "Associate of Engineering (A.E.)",
    "Associate of Applied Arts (A.A.A.)",
    "Diploma in Information Technology",
    "Certificate in Data Science",
    "Certificate in Project Management",
    "Certificate in Digital Marketing",
    "Certificate in Web Development",
    "Certificate in Graphic Design",
  ]

export default collegeDegrees