const userRoles = [
    "Software Engineer",
    "Data Scientist",
    "Network Administrator",
    "System Administrator",
    "DevOps Engineer",
    "Cloud Solutions Architect",
    "Database Administrator",
    "Front-End Developer",
    "Back-End Developer",
    "Full-Stack Developer",
    "Mobile App Developer",
    "Security Analyst",
    "UX/UI Designer",
    "Quality Assurance (QA) Engineer",
    "Machine Learning Engineer",
    "Artificial Intelligence (AI) Researcher",
    "Data Analyst",
    "Business Intelligence Analyst",
    "Network Engineer",
    "Systems Analyst",
    "IT Support Specialist",
    "Cybersecurity Analyst",
    "Hardware Engineer",
    "Embedded Systems Engineer",
    "Game Developer",
    "IT Project Manager",
    "Web Developer",
    "Software Architect",
    "Test Automation Engineer",
    "Cloud Engineer",
    "DevSecOps Engineer",
    "Product Manager",
    "Scrum Master",
    "Robotics Engineer",
    "Data Engineer",
    "Blockchain Developer",
    "Virtual Reality (VR) Developer",
    "Augmented Reality (AR) Developer",
    "3D Printing Engineer",
    "Big Data Engineer",
    "Network Security Engineer",
    "Systems Administrator",
    "Systems Engineer",
    "Computational Scientist",
    "Bioinformatics Analyst",
    "Geospatial Analyst",
    "Quantum Computing Researcher",
    "Control Systems Engineer",
    "Automation Engineer",
    "CAD (Computer-Aided Design) Designer"
]

export default userRoles